# minihomelib configuration file

# Set library file
#library_db: "library.sqlite"
library_db = "library_example.sqlite"

# ISBN processing with isbnlib
## Automatically fetch ISBN metadata
isbnlib_fetch_meta = true

# Fetch covers from OpenLibrary
openlibrary_fetch_cover = true
# Book cover size to fetch (one of "L", "M" or "S")
openlibrary_cover_size = "M"

# Alerts and notifications
## Past due alert duration (in days)
past_due = 30
## New book arrivals (in days)
new_arrival = 30

# Shelf management
## Default shelves
[shelves]
  "Study" = [
    "shelf 1",
    "shelf 2",
    "shelf 3",
  ]
  "Living room" = [
    "shelf 1",
  ]
  "Reading corner" = [
    "shelf 1",
  ]

