# minihomelib web UI translations

## Main user interface

[noscript]
  "en" = "This interface requires JavaScript. Please enable it in your browser."
  "zh-TW" = "本介面需使用JavaScript；請開啟。"

[title]
  "en" = "Library Management System"
  "zh-TW" = "圖書管理系統"

[page_generation_time_msg]
  "en" = "Page generated at"
  "zh-TW" = "頁面生成於"

[current_user]
  "en" = "Currently logged in as"
  "zh-TW" = "目前登入為"

[log_out]
  "en" = "Log out"
  "zh-TW" = "登出"

[add_book_form_button_title]
  "en" = "Show form for adding a book"
  "zh-TW" = "顯示新增圖書需填的表單"

[add_book_form_button_label]
  "en" = "Add a book"
  "zh-TW" = "新增圖書"

[checkin_checkout_button_title]
  "en" = "Check-in or check-out an existing book"
  "zh-TW" = "借閱或還回資料庫內圖書"

[checkin_checkout_button_label]
  "en" = "Check-out/Check-in"
  "zh-TW" = "借/還書"

[stats_label]
  "en" = "Stats"
  "zh-TW" = "統計"

[export_library_label]
  "en" = "Export library"
  "zh-TW" = "匯出書庫內容"

[export_transactions_label]
  "en" = "Export transactions"
  "zh-TW" = "匯出借還記錄"

[export_status_label]
  "en" = "Export book status"
  "zh-TW" = "匯出圖書狀態"

[add_book_bookname_label]
  "en" = "Book name: "
  "zh-TW" = "書名: "

[add_book_bookname_placeholder]
  "en" = "Name of book"
  "zh-TW" = "書名"

[add_book_authorname_label]
  "en" = "Author name: "
  "zh-TW" = "作者名: "

[add_book_authorname_placeholder]
  "en" = "Name of author"
  "zh-TW" = "作者名"

[add_book_acquisitiondate_label]
  "en" = "Book acquisition date: "
  "zh-TW" = "圖書取得日期: "

[add_book_source_label]
  "en" = "Source of book: "
  "zh-TW" = "圖書來源: "

[add_book_source_placeholder]
  "en" = "Source of book (e.g., bookstore name)"
  "zh-TW" = "圖書從哪裡獲得的(例: 書店名)"

[add_book_genre_label]
  "en" = "Genre: "
  "zh-TW" = "圖書分類: "

[add_book_genre_placeholder]
  "en" = "Genre of book (e.g., literature, science fiction)"
  "zh-TW" = "圖書分類(例: 文學、科幻)"

[add_book_location_label]
  "en" = "Book location: "
  "zh-TW" = "圖書位置: "

[add_book_location_placeholder]
  "en" = "Shelf where book belongs"
  "zh-TW" = "圖書該放在哪個架上"

[add_book_button_title]
  "en" = "Add book to database"
  "zh-TW" = "新增圖書至資料庫"

[add_book_button_label]
  "en" = "Add book"
  "zh-TW" = "確認新增"

[cancel_add_book_button_title]
  "en" = "Cancel book addition"
  "zh-TW" = "取消新增圖書"

[cancel_add_book_button_label]
  "en" = "Cancel"
  "zh-TW" = "取消"

[searchbox_placeholder_label]
  "en" = "Filter"
  "zh-TW" = "過濾"

[library_header]
  "en" = "Current library"
  "zh-TW" = "藏書"

[new_arrivals_header]
  "en" = "New arrivals"
  "zh-TW" = "新進圖書"

[book_table_name]
  "en" = "Name"
  "zh-TW" = "書名"

[book_table_author]
  "en" = "Author"
  "zh-TW" = "作者"

[book_table_language]
  "en" = "Language"
  "zh-TW" = "圖書語言"

[book_table_publisher]
  "en" = "Publisher"
  "zh-TW" = "出版者"

[book_table_pubyear]
  "en" = "Publication year"
  "zh-TW" = "出版年分"

[book_table_genre]
  "en" = "Genre"
  "zh-TW" = "分類"

[book_table_acquisitiondate]
  "en" = "Acquisition date"
  "zh-TW" = "取得日期"

[book_table_source]
  "en" = "Book source"
  "zh-TW" = "來源"

[book_table_location]
  "en" = "Book location"
  "zh-TW" = "圖書位置"

[book_table_lendstatus]
  "en" = "Lending status"
  "zh-TW" = "出借狀態"

[book_table_lasttransaction]
  "en" = "Last transaction"
  "zh-TW" = "最後出借或歸還日期"

[book_table_checkedout]
  "en" = "Checked out"
  "zh-TW" = "出借"

[book_table_checkedin]
  "en" = "Checked in"
  "zh-TW" = "歸還"

[book_table_cover]
  "en" = "Book cover"
  "zh-TW" = "封面"

[past_due_openquote]
  "en" = "Book '"
  "zh-TW" = "《"

[past_due_closequote]
  "en" = "' "
  "zh-TW" = "》"

[past_due_main]
  "en" = "checked out for over"
  "zh-TW" = "已出借超過"

[past_due_end_days]
  "en" = "days"
  "zh-TW" = "天"

## Login page

[login_title]
  "en" = "minihomelib - login"
  "zh-TW" = "圖書管理系統 - 登入"

[login_username]
  "en" = "User name"
  "zh-TW" = "使用者名稱"

[login_password]
  "en" = "Password"
  "zh-TW" = "密碼"

[login_submit]
  "en" = "Log in"
  "zh-TW" = "登入"

[login_add_user_message]
  "en" = "New user? Click <a href='adduser'>here</a> to register."
  "zh-TW" = "新用戶? 按<a href='adduser'>這裡</a>註冊。"

## Add user page

[adduser_title]
  "en" = "minihomelib - add user"
  "zh-TW" = "圖書管理系統 - 新增使用者"

[adduser_username]
  "en" = "User name"
  "zh-TW" = "使用者名稱"

[adduser_password]
  "en" = "Password"
  "zh-TW" = "密碼"

[adduser_password_confirm]
  "en" = "Confirm password"
  "zh-TW" = "確認密碼"

[adduser_submit]
  "en" = "Add user"
  "zh-TW" = "新增使用者"

## Stats page

[stats_title]
  "en" = "Library Management System - stats"
  "zh-TW" = "圖書管理系統 - 統計"

[stats_most_transactions]
  "en" = "Most checkout/checkins"
  "zh-TW" = "出借/還回最多次"

[stats_transactions]
  "en" = "transactions"
  "zh-TW" = "次"

[stats_longest_checkout]
  "en" = "Longest checkout"
  "zh-TW" = "出借最久"

## Message translations

[EinvalidISBN]
  "en" = "[ERROR] Invalid ISBN"
  "zh-TW" = "[錯誤] 非ISBN"

[EmissingISBN]
  "en" = "[ERROR] ISBN not in library"
  "zh-TW" = "[錯誤] 書庫中無此ISBN"

[EduplicateISBN]
  "en" = "[ERROR] Duplicate ISBN"
  "zh-TW" = "[錯誤] ISBN重複"

[Ebadlogin]
  "en" = "[ERROR] Login failed"
  "zh-TW" = "[錯誤] 登入失敗"

[Eduplicateusername]
  "en" = "[ERROR] User name already taken!"
  "zh-TW" = "[錯誤] 使用者名稱重複!"

[Iregistersuccess]
  "en" = "Successfully registered!"
  "zh-TW" = "登錄成功!"

[Ilogin]
  "en" = "Please log in."
  "zh-TW" = "請登入。"

[Iloggedout]
  "en" = "Logged out!"
  "zh-TW" = "已登出"